engines:
  fixme:
    enabled: true
  shellcheck:
    enabled: true
    exclude_fingerprints:
      - 6cfc3ceba4a3fdaf7765a096a0a6693c
      - 44f483960809cfdf739f7a0093ebdc38

ratings:
  paths:
    - "**.sh"
